name: Multi-Environment Terraform Plan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize and Plan
        run: |
          terraform init
          terraform plan -out=tfplan -input=false -no-color
          terraform show -no-color tfplan
        working-directory: .
